/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package userinterface.BloodBank;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ClinicOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.Hospital.HospitalManageOrganizationJPanel;

/**
 *
 * @author mitra
 */
public class BloodBankWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BloodBankWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account; 
    //BloodBankOrganization organization; 
    Enterprise enterprise; 
    EcoSystem business;

    public BloodBankWorkAreaJPanel(JPanel userProcessContainer, /* BloodBankOrganization bloodBankOrganization,*/ Enterprise enterprise, EcoSystem business,UserAccount account) {
      initComponents();
      this.userProcessContainer = userProcessContainer;
      this.account = account;
      //this.organization = bloodBankOrganization;
      this.enterprise = enterprise;
      this.business = business;
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBloodDonationResults = new javax.swing.JButton();
        btnEndUserBloodrequest = new javax.swing.JButton();

        setBackground(new java.awt.Color(133, 169, 143));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Blood Bank Work Area");

        btnBloodDonationResults.setBackground(new java.awt.Color(82, 91, 68));
        btnBloodDonationResults.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBloodDonationResults.setForeground(new java.awt.Color(255, 255, 255));
        btnBloodDonationResults.setText("Blood Donation Results");
        btnBloodDonationResults.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBloodDonationResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloodDonationResultsActionPerformed(evt);
            }
        });

        btnEndUserBloodrequest.setBackground(new java.awt.Color(82, 91, 68));
        btnEndUserBloodrequest.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEndUserBloodrequest.setForeground(new java.awt.Color(255, 255, 255));
        btnEndUserBloodrequest.setText("End User Blood Request");
        btnEndUserBloodrequest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEndUserBloodrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndUserBloodrequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEndUserBloodrequest)
                            .addComponent(btnBloodDonationResults, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1)))
                .addContainerGap(472, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBloodDonationResults, btnEndUserBloodrequest});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(btnBloodDonationResults, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnEndUserBloodrequest, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBloodDonationResults, btnEndUserBloodrequest});

    }// </editor-fold>//GEN-END:initComponents

    private void btnBloodDonationResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloodDonationResultsActionPerformed
        // TODO add your handling code here:
         BloodDonationResultsJPanel bloodDonationResultsJPanel = new BloodDonationResultsJPanel(userProcessContainer, enterprise.getOrganizationDirectory(),enterprise,account,business);
        userProcessContainer.add("BloodDonationResultsJPanel", bloodDonationResultsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBloodDonationResultsActionPerformed

    private void btnEndUserBloodrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndUserBloodrequestActionPerformed
        // TODO add your handling code here:
         ManageBloodRequestJPanel manageBloodRequestJPanel = new ManageBloodRequestJPanel(userProcessContainer, enterprise.getOrganizationDirectory(),enterprise,account,business);
        userProcessContainer.add("ManageBloodRequestJPanel", manageBloodRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnEndUserBloodrequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBloodDonationResults;
    private javax.swing.JButton btnEndUserBloodrequest;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
